### ISSUE TITLE
Is not finding terms in oppearing only in titles

### ISSUE THREAD

**Issue by bibliotechy** [tulibraries/arrogate#2]
If you enter a term that is only in the title of a guide, it does not return that guide as a search result. I don't think that guides are indexed.

**Comment by bibliotechy** [comment]
For example, [this guide](http://guides.temple.edu/EDAD5552_bb) is in the search index, but [you can't find it with the term EDAD5552](http://libqa.library.temple.edu/libguide_search/?q=EDAD5552&search_field=all_fields)

**Comment by skng5** [comment]
Titles are not being indexed in Guiding Light. Addressed in https://github.com/tulibraries/guiding_light/compare/fix_title_search?expand=1

**Comment by bibliotechy** [comment]
Fixed by https://github.com/tulibraries/guiding_light/issues/3
