### ISSUE TITLE
Decomission Arrogate

### ISSUE THREAD

**Issue by bibliotechy** [tulibraries/arrogate#9]
Arrogate is still running at https://libqa.library.temple.edu/libguide_search/ but we want to shut it down.

Steps to decommission

- [x] Check with Olivia
- [x] Export Remaining Highlighted links as CSV
- [ ] Remove solr process from libqa, including init.d
- [ ] Remove Arrogate code
- [ ] Remove arrogate config from httpd

**Comment by bibliotechy** [comment]
Olivia has asked for the remaining highlighted links to be exported as csv. CSV should look like

| Page Name | Author | Link | Has Diamond Non-Permanent Link | Has Diamond Permanent Link | Has Journal Finder Link | Has Summon | 
| ---- | ---- | ---- | ---- | ---- | ---- | ---- |
| Research Guides: Photography: Write | Jill Luedke | https://guides.temple.edu/c.php?g=78017&p=515362 | 5 |1 | 0 | 0 |
...

This could be extracted from the fcated index JSON response such as https://libqa.library.temple.edu/libguide_search/?f[link_facet][]=Has+Diamond+Non-Permanent+links&format=json

**Comment by cmharlow** [comment]
The only infrastructure involved here is that this is hiding on the libqa box... by which we mean, cob-beta-app-1? cob-beta-app-2? lurch? cob-qa-solr-1?

**Comment by bibliotechy** [comment]
The TUCloud machine "libqa". The rails app and solr are both running there and con now be removed.

**Comment by cmharlow** [comment]
See tulibraries/tul_cob_playbook#100 - libqa is marked for decommissioning. this (i believe) preempts the work @nomadicoder may / may not have started. @bibliotechy @nomadicoder anything to add, or just close this ticket?

**Comment by bibliotechy** [comment]
We can just close as all those other tasks will be taken care of when the box is decommissioned.

:bomb: arrogate :bomb:
